# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
spear_ <- function(family, Y, X, Yobs, Xobs, Z, nclasses, functional_path, pattern_samples, pattern_features, weights, num_factors, warm_up, max_iter, thres_elbo, thres_count, thres_factor, a0, b0, a1, b1, a2, b2, lower, print_out, interceptsX, interceptsY, post_mu, post_sigma2, post_pi, post_tmuX, post_tsigma2X, post_tpiX, post_tmuY, post_tsigma2Y, post_tpiY, tauY, tauZ, log_pi, log_minus_pi, nuXmat, nuYmat, post_a0, post_b0, post_a1, post_b1, post_a2x, post_b2x, post_a2y, post_b2y, meanFactors, seed0) {
    invisible(.Call('_SPEARcomplete_spear_', PACKAGE = 'SPEARcomplete', family, Y, X, Yobs, Xobs, Z, nclasses, functional_path, pattern_samples, pattern_features, weights, num_factors, warm_up, max_iter, thres_elbo, thres_count, thres_factor, a0, b0, a1, b1, a2, b2, lower, print_out, interceptsX, interceptsY, post_mu, post_sigma2, post_pi, post_tmuX, post_tsigma2X, post_tpiX, post_tmuY, post_tsigma2Y, post_tpiY, tauY, tauZ, log_pi, log_minus_pi, nuXmat, nuYmat, post_a0, post_b0, post_a1, post_b1, post_a2x, post_b2x, post_a2y, post_b2y, meanFactors, seed0))
}

